### ISSUE TITLE
Editor plugins

### ISSUE THREAD

**Issue by purcell** [hjwylde/git-fmt#39]
Ideally I'd have an Emacs plugin which will run `omnifmt` on the current file whenever I save it, and `omnifmt` will use its smarts to Do The Right Thing in the context of my current project.  I'll happily write such a plugin when the time comes.

**Comment by hjwylde** [comment]
Sounds good, I suspect the "context of my current project" will just mean relative to the nearest `.omnifmt.yaml` config file, or the default one.

**Comment by purcell** [comment]
Yup, exactly.

**Comment by hjwylde** [comment]
I've extracted out the omnifmt library components and created a binary for it that has nothing to do with git -> https://github.com/hjwylde/omnifmt.

Will make a 0.1.0.0 release for it soon to trial and error before updating this project to use it.

**Comment by hjwylde** [comment]
https://github.com/hjwylde/vim-omnifmt
